openapi: 3.0.3
info:
  title: Notes API
  version: 1.0.0
  description: API documentation for the Notes App backend
servers:
  - url: http://localhost:3000
    description: Local
tags:
  - name: Auth
  - name: Notes
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Note:
      type: object
      properties:
        _id: { type: string }
        title: { type: string }
        content: { type: string }
        user: { type: string }
        createdAt: { type: string, format: date-time }
paths:
  /api/auth/signup:
    post:
      tags: [Auth]
      summary: Sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '201':
          description: Created
  /api/auth/login:
    post:
      tags: [Auth]
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: OK
  /api/notes:
    get:
      tags: [Notes]
      summary: Get notes with pagination
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, default: 10 }
      responses:
        '200':
          description: OK
    post:
      tags: [Notes]
      summary: Create a new note
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, content]
              properties:
                title: { type: string }
                content: { type: string }
      responses:
        '201':
          description: Created
  /api/notes/{id}:
    get:
      tags: [Notes]
      summary: Get a single note
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
        '404':
          description: Not found
    put:
      tags: [Notes]
      summary: Update a note
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                content: { type: string }
      responses:
        '200':
          description: Updated
        '404':
          description: Not found
    delete:
      tags: [Notes]
      summary: Delete a note
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Deleted
        '404':
          description: Not found
